backend/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for,abort, current_app, jsonify
from flask_login import login_required, current_user
from .models import Post, Discussions, IMG, UserDiscussionVote, Comment
from . import db
from werkzeug.utils import secure_filename
from sqlalchemy.exc import IntegrityError
import os

views = Blueprint('views', __name__)

UPLOAD_FOLDER = r'backend\website\static\images\UPLOADED IMG'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@views.route('/')
def home():
    return render_template("Homepage.html", user=current_user)

@views.route('/start-recycling-categories')
def SRCategories():
    return render_template("SRCategories.html", user=current_user)


@views.route('/start-recycling-plastic')
def SRPlastic():
    return render_template("SR-Plastic.html", user=current_user)

@views.route('/start-recycling-paper')
def SRPaper():
    return render_template("SR-Paper.html", user=current_user)

@views.route('/start-recycling-textile')
def SRTextile():
    return render_template("SR-Textile.html", user=current_user)

@views.route('/start-recycling-glass')
def SRGlass():
    return render_template("SR-Glass.html", user=current_user)

@views.route('/forum')
def forum():
    discussions = Discussions.query.all()
    return render_template("Forum.html", user=current_user, discussions=discussions)

@views.route('/createForum', methods=['GET', 'POST'])
@login_required
def forumClicked():
    if request.method == "POST":
        dTitle = request.form.get('discussionTitle')
        dDescription = request.form.get('discussionDescription')
        pic = request.files['pic']

        if not all([dTitle, dDescription]):
            flash('Please fill up all the required forms', category='error')
        elif len(dTitle) > 70:
            flash('Title reached maximum limit of characters', category='error')
        elif pic and allowed_file(pic.filename):
            try:
                filename = secure_filename(pic.filename)
                mimetype = pic.mimetype

                # Save the file to the designated folder
                file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                pic.save(file_path)

                # Save the filename to the database
                new_image = IMG(img_filename=file_path, name=filename, mimetype=mimetype, user_id=current_user.id)
                db.session.add(new_image)
                db.session.commit()

                # Create a new discussion associated with the uploaded image
                new_discussion = Discussions(
                    dTitle=dTitle, 
                    dDescription=dDescription,
                    user_id=current_user.id,
                    image_id=new_image.id
                )
                db.session.add(new_discussion)
                db.session.commit()

                flash('Discussion created!', category='success')
                return redirect(url_for('views.forumPost', discussion_id=new_discussion.id))
                
            except IntegrityError as e:
                db.session.rollback()
                if 'UNIQUE constraint failed: img.img' in str(e):
                    flash('Image file name is not unique', category='error')
                else:
                    flash('An error occurred during discussion creation', category='error')

    return render_template("Create-Forum.html", user=current_user)


@views.route('/Discussion/<int:discussion_id>')
def forumPost(discussion_id):
    discussion_data = Discussions.query.get(discussion_id)

    if not discussion_data:
        abort(404)

    return render_template("Forum-Clicked.html", user=current_user, discussion_data=discussion_data)

@views.route('/like_dislike/<int:discussion_id>', methods=['POST'])
@login_required
def like_dislike(discussion_id):
    discussion = Discussions.query.get(discussion_id)

    if not discussion:
        return jsonify({'error': 'Discussion not found'}), 404

    is_like = request.json.get('is_like')

    if is_like is None:
        return jsonify({'error': 'Invalid request'}), 400

    # Check if the user has already voted on this discussion
    existing_vote = UserDiscussionVote.query.filter_by(user_id=current_user.id, discussion_id=discussion_id).first()

    try:
        if existing_vote:
            # If the user has already voted, update their vote only if the new vote is different
            if existing_vote.is_like != is_like:
                existing_vote.is_like = is_like
            else:
                # If the user votes the same as their previous vote, remove the vote
                db.session.delete(existing_vote)
        else:
            # If the user hasn't voted, create a new vote
            new_vote = UserDiscussionVote(user_id=current_user.id, discussion_id=discussion_id, is_like=is_like)
            db.session.add(new_vote)

        # Update the discussion likes and dislikes count
        discussion.likes = UserDiscussionVote.query.filter_by(discussion_id=discussion_id, is_like=True).count()
        discussion.dislikes = UserDiscussionVote.query.filter_by(discussion_id=discussion_id, is_like=False).count()

        db.session.commit()

        return jsonify({'likes': discussion.likes, 'dislikes': discussion.dislikes}), 200
    except Exception as e:
        print(e)
        db.session.rollback()
        return jsonify({'error': 'Failed to update like/dislike'}), 500

@views.route('/submit_comment/<int:discussion_id>', methods=['POST'])
@login_required
def submit_comment(discussion_id):
    try:
        # Get the comment text from the request
        comment_text = request.form.get('commentText')

        # Validate the comment text (you can add more validation if needed)

        # Create a new comment associated with the discussion
        new_comment = Comment(
            text=comment_text,
            user_id=current_user.id,
            discussion_id=discussion_id
        )
        db.session.add(new_comment)
        db.session.commit()

        # Return a success message
        return jsonify({'message': 'Comment submitted successfully'}), 200
    except Exception as e:
        print(e)
        return jsonify({'error': 'Failed to submit comment'}), 500

@views.route('/post')
@login_required
def post():
    return render_template("Post-page.html", user=current_user) 

@views.route('/login')
def login():
    return render_template("Login.html", user=current_user)

@views.route('/create-post', methods=['GET', 'POST'])
@login_required
def CreatePost():
    if request.method == "POST":
        category = request.form.get('chosenCat')
        title = request.form.get('postTitle')
        description = request.form.get('postDescription')
        instruction_title = request.form.get('instructionTitle')
        instruction_description = request.form.get('stepDescription')
        reference = request.form.getlist('references[]')
        pic = request.files['pic']

        if not all([category, title, description, instruction_title, instruction_description, reference]):
            flash('Please fill up all the required forms', category='error')
        elif len(title) > 70:
            flash('Title reached maximum limit of characters', category='error')
        elif len(instruction_title) > 70:
            flash('Instruction title reached maximum limit of characters', category='error')
        elif pic and allowed_file(pic.filename):
            try:
                filename = secure_filename(pic.filename)
                mimetype = pic.mimetype

                file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                pic.save(file_path)

                new_image = IMG(img_filename=file_path, name=filename, mimetype=mimetype, user_id=current_user.id)
                db.session.add(new_image)
                db.session.commit()

                new_post = Post(
                    category=category, 
                    title=title,
                    description=description,
                    instruction_title=instruction_title,
                    instruction_description=instruction_description,
                    user_id=current_user.id,
                    image_id=new_image.id)
                db.session.add(new_post)
                db.session.commit()
                flash('Post created!', category='success')
                return redirect(url_for('views.CreatePost'))
            except IntegrityError as e:
                db.session.rollback()
                if 'UNIQUE constraint failed: img.img' in str(e):
                    flash('Image file name is not unique', category='error')
                else:
                    flash('An error occurred during discussion creation', category='error')

    return render_template("Create-Post.html", user=current_user)

@views.route('/account')
@login_required
def account():
    return render_template("Account.html", user=current_user) 

backend/website/templates/Forum.html
{% extends "base.html" %} {% block title %}Forum{% endblock %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Forum.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap">
    <link rel="shortcut icon" href="/src/img/Logo/NGOlogo.png" type="image/x-icon">

</head>

<body style="background-color: #F4F4F4;">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>


{% block content %}
<!-- FORUM -->
<!-- BANNER SEARCH -->
<div class="banner-bg-plastic section p-5 text-center" style="background-image: url(static/images/background/account.jpg);">
    <div class="container" style="padding-block: 50px;">
        <div>
            <p class="h1 title">Forum</p>
            <p class="text-white mx-5 px-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium id sequi molestiae dolor delectus aliquid odit libero nisi quidem at saepe, laudantium eius. Nostrum inventore porro mollitia sint, iure a.</p>
            <form class="d-flex justify-content-center" action="{{ url_for('views.forumClicked') }}" method="GET">
                <button class="btn btn-createnewtopic m-0">Create new topic</button> 
            </form>
        </div>
    </div>
</div>

<!-- Latest -->
<div class="discussion container" style="background-color: white; margin-top: 2%; padding: 3%; margin-bottom: 2%;">
    <div class="row justify-content-center">
        <p class="label h1">Discussion</p>
        <hr>
        <div class="row topic">
            {% if discussions|length > 0 %}
                {# Get the latest discussion by accessing the last element in the discussions list #}
                {% set latest_discussion = discussions[-1] %}
                
                <div class="card topic mb-3">
                    <div class="row my-3 mx-2">
                        <div class="col">
                            <!-- Link to discussion page -->
                            <a href="{{ url_for('views.forumPost', discussion_id=latest_discussion.id) }}">
                                <h4 class="card-title topic" style="margin-top: 10px;">{{ latest_discussion.dTitle }}</h4>
                            </a>
                        </div>
                        <div class="col" style="margin-top: 5px;">
                            <p class="author">
                                by: {{ latest_discussion.user.username }}
                            </p>
                            <p class="date-time">
                                {{ latest_discussion.date.strftime('%B %d, %Y %I:%M %p') }}
                            </p>
                        </div>
                        <div class="col">
                            <p class="comment">
                                30 comments <!-- You may replace this with the actual comment count -->
                            </p>
                            <p class="like">
                                {{ latest_discussion.likes }} likes <!-- You may replace this with the actual like count -->
                            </p>
                        </div>
                    </div>
                </div>
            {% else %}
                <p>No discussions yet.</p>
            {% endif %}
        </div>
    </div>   
</div>


<!-- Discussion -->
<div class="discussion container" style="background-color: white; margin-top: 2%; padding: 3%; margin-bottom: 2%;">
    <div class="row justify-content-center">
        <p class="label h1">Discussion</p>
        <hr>
        <div class="row topic">
            {% if discussions|length > 0 %}
                {% for discussion in discussions %}
                    <div class="card topic mb-3">
                        <div class="row my-3 mx-2">
                            <div class="col">
                                <!-- Link to discussion page -->
                                <a href="{{ url_for('views.forumPost', discussion_id=discussion.id) }}">
                                    <h4 class="card-title topic" style="margin-top: 10px;">{{ discussion.dTitle }}</h4>
                                </a>
                            </div>
                            <div class="col" style="margin-top: 5px;">
                                <p class="author">
                                    by: {{ discussion.user.username }}
                                </p>
                                <p class="date-time">
                                    {{ discussion.date.strftime('%B %d, %Y %I:%M %p') }}
                                </p>
                            </div>
                            <div class="col">
                                <p class="comment">
                                    30 comments <!-- You may replace this with the actual comment count -->
                                </p>
                                <p class="like">
                                    {{ discussion.likes }} likes <!-- You may replace this with the actual like count -->
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No discussions yet.</p>
            {% endif %}
        </div>
    </div>   
</div>

<!-- FOOTER -->
<footer class="footer pt-5 pb-2 position-relative">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-6 col-xl-6 text-center text-md-start mx-auto mt-3">
                <p class="h4 brand">Upcycle</p>
                <p class="description">This website combines insightful articles on ways to reuse recyclable materials with engaging forums for a community of recyclers, all in one place. Explore to stay informed and join forums to connect!</p>
            </div>
            <div class="col-md-4 col-lg-4 col-xl-4 text-center text-md-start mx-auto mt-3">
                <p class="h4 link">Link</p>
                <ul class="footer-links">
                    <li><a class="footer" href="">About Us</a></li>
                    <li><a class="footer" href="">Contact Us</a></li>
                    <li><a class="footer" href="">Home</a></li>
                    <li><a class="footer" href="">FAQ</a></li>
                </ul>
            </div>
            <div class="row text-center g-4">
                <p class="copyright">© 2024 Upcycle</p>
            </div>
        </div>
    </div>
</footer>
{% endblock content %}

</body>
</html>

backend/website/templates/Login.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages%}
        {% for category, messages in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin: 0px;">
                    {{ messages }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin: 0px;">
                    {{ messages }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}     
        {% endfor %}
    {% endif %}
{% endwith %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Upcyle - Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Login.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">  
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

    <!-- START HERE -->
    <div class="section banner-info">
        <div class="container-fluid" >
            <div class="inside-orange-banner">
                <div class="row">
                    <div class="col-lg-7 col-sm-12 description py-4 text-center" style="background-color: #F4F4F4;">
                        <!-- LEFT SIDE -->
                        <div class="p-5">
                            <a href="{{ url_for('views.home') }}">
                            <img class="brand_img img-fluid" src="{{ url_for('static', filename='images/upcycle-brand.png')}}" alt="">
                            </a>
                            <h1>Login to Your Account</h1>
                            <p>Get started by logging in Upcycle!</p>
                            <!-- <div class="col"><img class="img-fluid" src="/images/socmed_icons.png" alt="" style="width: 150px;"></div>
                            <div class="col"><img class=" img-fluid" src="/images/login_or.png" alt="" style="width: 70%"></div> -->
                            
                            <form method="POST">
                                <div class="mt-5">
                                    <!-- Add the email form -->
                                <div class="form-group">
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                                </div>

                                <div class="form-group">
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
                                </div>

                                <div class="signup1-button">
                                    <button class="custom-login-button" onclick="redirectToAccount()">Log In</button>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                    <!-- RIGHT SIDE -->
                    <div class="col-lg-5 col-sm-12 img-right d-flex justify-content-center align-items-center p-5" style="background-image: url(static/images/background/login.png);">
                        <div class="login_to-sign-in">
                            <div class="row">
                                <div class="col text-center">
                                    <!-- <img class="position-absolute h-100 w-100" style="object-fit: fill" src="src/login_bg.png" alt=""> -->
                                    <h1 class="new-here-text">New Here?</h1>
                                    <p class="signup-message">Sign-up and join our community!</p>
                                    <a href="/signup" id="sign_up">
                                        <button class="signup-button">Sign up</button>
                                    </a>
                                    
                                </div>
                                <script src="connection.js"></script>
                            </div>
                            
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>
</html>

backend/website/templates/Signup.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages%}
  {% for category, messages in messages %}

  {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin: 0px;">
        {{ messages }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% else %}
      <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin: 0px;">
        {{ messages }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>    
  {% endif %}
  {% endfor %}
{% endif %}
{% endwith %}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Upcyle - Sign Up</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Signup.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">     
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

<!-- START HERE -->
<div class="section banner-info">
    <div class="container-fluid" >
        <div class="inside-orange-banner">
            <div class="row">
                <div class="description col-xl-7 col-lg-6 col-sm-12 col-md-12 py-4 text-center" style="background-color: #F4F4F4;">
                <!-- LEFT SIDE -->
                    <form method="POST">
                    <div class="bg px-5">
                        <a href="{{ url_for('views.home') }}">
                        <img class="brand_img img-fluid" src="{{ url_for('static', filename='images/upcycle-brand.png')}}" alt="">
                        </a>
                        <h1>Sign Up</h1>
                        <p class="mx-5">Sign up now and become a part of something amazing!</p>
                        <div class="my-5"></div>
                        <div class="mt-4"></div>
                        <p class="h5 text-start">Create your Account:</p>
                        <div class="container mt-4">
                            <div class="form-group mb-3">
                                <input type="text" class="form-control" id="userName" name="userName" placeholder="Username">
                            </div>

                            <div class="form-group mb-3">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                            </div>
        
                            <div class="form-group mb-3">
                                <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter Password">
                            </div>
        
                            <div class="form-group mb-3">
                                <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
                            </div>
        
                        </div>
                        <div class="signup1-button">
                            <button class="custom-signup-button" >Sign Up</button>
                        </div>
                    </div>
                    </form>
                </div>
                
                <!-- RIGHT SIDE -->
                <div class="right-side col-xl-5 col-lg-6 col-sm-12 img-left d-flex justify-content-center align-items-center p-5" style="background-image: url(static/images/background/signup.png);">
                    <div class="login_to-sign-in">
                        <div class="row">
                            <div class="col text-center">
                                <h1 class="new-here-text">WELCOME TO UPCYCLE!</h1>
                                <p class="signup-message">Have an existing account? </p>
                                <a href="/login" id="login">
                                    <button class="signup-button">Log In</button>
                                </a>
                            </div>
                            <script src="connection.js"></script>
                        </div>
                        
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

</body>
</html>